exp_name: "circulant_8n"
num_runs: 5

simulation:
  num_agents: 20
  num_steps: 100

graph:
  type: "circulant"
  neighbors: 8

initial_population:
  susceptible: 0.9
  exposed: 0.05
  infectious: 0.05
  recovered: 0.0