exp_name: "lattice"
num_runs: 10

simulation:
  num_agents: 100
  num_steps: 100

graph:
  type: "lattice"
  rows: 10
  cols: 10

initial_population:
  susceptible: 0.9
  exposed: 0.05
  infectious: 0.05
  recovered: 0.0